### ISSUE TITLE
Support optional "t2 unlimited" attribute when Starting a t2 Instance

### ISSUE THREAD

**Issue by tangerinedream** [tangerinedream/AWS_EC2_Scheduler#22]
Support the new t2 Unlimited feature.

Requirements:
When starting an instance of type t2, support optional ability to start as t2 Unlimited
When scaling from t2 to any other instance type, ensure Unlimited attribute is unset, as this may cause a Start Instance failure.

Specification:
Currently, instance types in DynamoDB are specified as:
{ <profile_name>: <instance_family>.<instance_size>  }

For example
...
  "TierScaling": {
    "default": "t2.nano",
    "profileB": "t2.medium",
    "profileC": "t2.large",
    "profileD": "c4.large"
  },
...

Allow the specification of Unlimted by supporting the following syntax ".U" after the instance_size

T2 Unlimited is referenced here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html

{ <profile_name>: <instance_family>.<instance_size>[.Uu]  }

For example:
...
  "TierScaling": {
    "default": "t2.nano.U",
    "profileB": "t2.medium",
    "profileC": "t2.large.u",
    "profileD": "c4.large"
  },
...

Notice:
The default and profileC should enable Unlimited attribute, however profileB should Start t2 without Unlimited attribute.
Both "U" and "u" are supported

**Comment by igordavid** [comment]
Hi @tangerinedream ,

PR has been created with this feature:

https://github.com/tangerinedream/AWS_EC2_Scheduler/pull/24
