### ISSUE TITLE
Feature Request to Start a subset of instances within a Tier

### ISSUE THREAD

**Issue by tangerinedream** [tangerinedream/AWS_EC2_Scheduler#3]
Currently the product will Start all instances within a Tier.  For example, if you have 6 web servers in the Web Tier, the product will Start all 6.  However, there are some cases where you don't need all 6 started, for example unit testing.  In those cases, it would be helpful to enhance the Profile feature, to allow for the specification of either or both of:

- % of instances to be started (e.g. 20% of the Tier)

- Specific number of instances to be started (e.g 2)

The Scheduler could calculate this automatically and thereby allow for improved cost management

**Comment by tangerinedream** [comment]
As this enhancement would be on a tier by tier basis, we would need to account for it in the DynamoDB TierSpecification table, which notionally looks like this:

```
{
  "SpecName": "BotoTestCase1",
  "TierStart": {
    "TierSequence": "2",
    "TierSynchronization": "False"
  },
  "TierStop": {
    "TierSequence": "0",
    "TierStopOverrideFilename": "/tmp/StopOverride",
    "TierStopOverrideOperatingSystem": "Linux",
    "TierSynchronization": "False",
    "InterTierOrchestrationDelay": "10"
  },
  "TierScaling": {
    "default": "t2.nano",
    "profileB": "t2.medium",
    "profileC": "t2.large",
    "profileD": "c4.large"
  },
  "TierTagValue": "Role_Web"
}
```

What might be reasonable is to extend the TierScaling construct to account for including a Fleet (aka Tier) Subset indicator.  This indicator would bind the the number of instances to Start to a particular Scaling Profile, which intuitively makes sense.  Perhaps a construct like the following:

```
{
  "SpecName": "BotoTestCase1",
  "TierStart": {
    "TierSequence": "2",
    "TierSynchronization": "False"
  },
  "TierStop": {
    "TierSequence": "0",
    "TierStopOverrideFilename": "/tmp/StopOverride",
    "TierStopOverrideOperatingSystem": "Linux",
    "TierSynchronization": "False",
    "InterTierOrchestrationDelay": "10"
  },
  "TierScaling": {
      "default": {
          "InstanceType" : "t2.nano"
      },
     "profileB": {
          "InstanceType" : "t2.medium",
          "FleetSubset" : "100%"
      },
     "profileC": {
          "InstanceType" : "t2.large",
          "FleetSubset" : "40%"
      },    
     "profileD": {
          "InstanceType" : "c4.large",
          "FleetSubset" : "5"
      }
  },
  "TierTagValue": "Role_Web"
}
```
There are a few things to note here:

- "FleetSubset" is an _optional attribute_ and would implicitly default to 100%.  This is demonstrated by the Scaling Profile named "default".

- The value of FleetSubset can be an absolute value or a percentage (percentages would round up)

-  Percentage values over 100% would be treated as 100% (e.g. 125% is 100%)

- For absolute values, the Orchestrator would start _up to_ the specified number of instances specified.  However, there may not be that many instances in the fleet to begin with.  For example, profileD indicates "5" instances should be started.  However, if there are only 3 instances in the fleet, only 3 would be Started.

- The FleetSubset would have no effect on Stopping the tier.  All instances would be Stopped when the Stop Action is provided.

- Some algorithm should be used to prefer to Start instances based on multi-AZ.  For example, with 4 instances total in the Fleet (e.g. Tier), 2 in AZ-1a, 1 in AZ-1b, and 1 in AZ-1c, the following should occur:
-- FleetSubset set to 50% should start no more than 1 in two of the AZs.
-- FleetSubset set to 3 should start 1 per AZ.

**Comment by igordavid** [comment]
Hi @tangerinedream ,

Here is the first draft:

https://github.com/igordavid/AWS_EC2_Scheduler/tree/feature/Start_subset_of_fleet

It should cover all the features except balancing in AZs, as we may also want to discuss if we want to prefer certain instances for starting. 

Also, we may discuss percentages and rounding, for example if we choose to round the python way (method "round") and we have 2 instances, we would need to choose 75% to start both of them (everything below 75% will start one instance only)

**Comment by tangerinedream** [comment]
Hi @igordavid,

Can you create a Pull request so I can better see the proposed changes?

Regarding rounding, I would suggest we "round up".  In your example, I would expect the following:
0% == 0 instances,
25% - 50% == 1 instance
50% + == 2 instances

**Comment by tangerinedream** [comment]
This has been implemented
